[package]
name = "localcg"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[dependencies]
gtk = "^0.5.0"
gdk = "^0.9.0"
relm = "^0.15.0"
relm-derive = "^0.15.0"
localc = { git = "https://github.com/lausek/localc.git" }
